# SPDX-FileCopyrightText: 2025 Shun Sakai
#
# SPDX-License-Identifier: GPL-3.0-or-later

[tool.bumpversion]
current_version = "0.1.2"

[[tool.bumpversion.files]]
filename = "docs/man/man1/ngrv.1.adoc"
